### ISSUE TITLE
Add node number metric for cluster usecase

### ISSUE THREAD

**Issue by imker25** [imker25/samba_exporter#101]

**Comment by imker25** [comment]
Fixed with 200eff9971c0a7081ad9c7d41e0d487fd60665c7 on main. Can be previewed with [V1.28.1-pre](https://github.com/imker25/samba_exporter/releases/tag/1.28.1-pre)

**Comment by copenlc** [comment]
Hey @imker25 starting to test this out now and build a new dashboard with the new data,  Just a heads up looks like theres a typo for one of the metrics.  ( porcesses ) 

# HELP samba_porcesses_per_node_count Number of Locks per cluster node
# TYPE samba_porcesses_per_node_count gauge
samba_porcesses_per_node_count{node="0"} 7
samba_porcesses_per_node_count{node="1"} 2415
samba_porcesses_per_node_count{node="2"} 235
samba_porcesses_per_node_count{node="3"} 3378

**Comment by imker25** [comment]
Hello @copenlc ,
thanks for testing the new feature. Ans also thanks for the hint to the typO. I will fix this with the next `-pre` release. 

According your question. Yes, you can see the list of all exported metrics on the man page of the samba_exporter.

So with the command `man samba_exporter` you should be able to see the man page. There you can find a section `Exported values`  that gives information on all exported metrics. The metrics additionally exported when samba is detected to be running in cluster mode are listed in the `smbd in cluster mode` section.

You should be abe to see this on the machine you are running the `-pre`  release version.
The [published man page](https://imker25.github.io/samba_exporter/manpages/samba_exporter.1.html) will be updated once V1.28.x is not a pre release anymore.

**Comment by imker25** [comment]
Fixed with [V1.28.5](https://github.com/imker25/samba_exporter/releases/tag/1.28.5) release
