### ISSUE TITLE
Option to disable generation of samba_locks_per_share_count.

### ISSUE THREAD

**Issue by crocchietta** [imker25/samba_exporter#126]
Good morning.
Would it be possible to add an option, like _-not-expose-client-data_, to disable the generation of the _samba_locks_per_share_count_ metric?

Depending on the number of shares of the SAMBA server, the _share=_ label can generate a high cardinality. In my case, in a professional environment, I have samba servers exposing more than 50 shares.

**Comment by imker25** [comment]
@crocchietta you can try the feature with [V1.32.1-pre](https://github.com/imker25/samba_exporter/releases/tag/1.32.1-pre)

**Comment by crocchietta** [comment]
Good morning.
thank you for this addition. I don't have an environment available to compile GO language.
Do you have an idea of ​​a date for the next version?

Otherwise in general, it would be good to systematically provide an option allowing you to choose or not to generate metrics that could result in high cardinality. While allowing the generation of summary metrics.

**Comment by crocchietta** [comment]
I hadn't noticed that the preview versions were also compiled...

**Comment by imker25** [comment]
@crocchietta 

> I hadn't noticed that the pre release were also compiled...+

Yes, on the [page](https://github.com/imker25/samba_exporter/releases/tag/1.32.1-pre) of V1.32.1-pre you can find installable packages. 

> Otherwise in general, it would be good to systematically provide an option allowing you to choose or not to generate metrics that could result in high cardinality. While allowing the generation of summary metrics.

So you suggest a new option that sets all `-not-expose-*`  parameters to true?

**Comment by crocchietta** [comment]
No. I suggest that for future metrics that may generate high cardinality due to labels, to always consider adding an option to disable this metrics or just these labels (depending on the cases).

**Comment by crocchietta** [comment]
Is this change included in the new version 1.32.9?

**Comment by imker25** [comment]
@crocchietta yes it is

**Comment by imker25** [comment]
Fix released with [V1.32.9](https://github.com/imker25/samba_exporter/releases/tag/1.32.9)
